apiVersion: v1beta
cartographer:
  address: 0.0.0.0
  port: 8080
  web:
    address: 0.0.0.0
    port: 8081
    siteName: "Cartographer"
  backend:
    type: boltdb
    path: /data/cartographer.db
links: 
  - url: https://kernel.org
    description: "kubernetes main github repo"
    tags: ["linux"]
  - id: example1
    data:
      example: data
      list:
      - item1
      - item2
      - item3
  - id: example2
    data:
      example: data2
      list:
      - item1
      - item2
      - item3
